image: node:12

stages:
  - check
  - build
  - test

NPM Audit:
  stage: check
  allow_failure: true
  script:
    - npm audit

Static Test:
  stage: check
  before_script:
    - npm ci
  script:
    - npm run test:static

Build:
  stage: build
  before_script:
    - npm ci
  script:
    - npm build

Unit Test:
  stage: test
  before_script:
    - npm ci
  script:
    - npm test
